### ISSUE TITLE
Windows libraries / headers / cmake package are not installed in %LIBRARY_PREFIX%

### ISSUE THREAD

**Issue by sdebionne** [conda-forge/tbb-feedstock#86] opened 2021-05-26 15:37 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Installation of the libraries on Windows should be installed in %LIBRARY_PREFIX%. Quoting the [documentation](https://docs.conda.io/projects/conda-build/en/stable/user-guide/environment-variables.html#environment-variables-set-during-the-build-process):

> Unix-style packages on Windows, which are usually statically linked to executables, are built in a special `Library` directory under the build prefix.

<br/>
Environment (<code>conda list</code>):
<details>

```
conda list tbb
# packages in environment at C:\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
tbb                       2021.2.0             h2d74725_0    conda-forge
tbb-devel                 2021.2.0             h2d74725_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test
    active env location : C:\Miniconda3\envs\test
            shell level : 2
 populated config files :
          conda version : 4.10.1
    conda-build version : 3.18.11
         python version : 3.7.4.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Miniconda3  (writable)
      conda av data dir : C:\Miniconda3\etc\conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
       envs directories : C:\Miniconda3\envs
               platform : win-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.4 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by AlexVeprev** [comment] 2021-05-27 08:27
@sdebionne, good catch, thank you! Thank you for the PR as well.
@mgouicem, seems it is the root cause of the layout problem we recently talked about.

I agree that it should be fixed, but let me better understand the impact of such change, at least I need to check default/common `CMAKE_PREFIX_PATH`. I'll appreciate if you have some thoughts on it as active users.

**Comment by sdebionne** [comment] 2021-05-27 09:06
It looks like the changes are a little more involved than I would have thought, aka changing `CMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%` breaks the installation of the python package. Might be an issue with the upstream package though...

**Comment by AlexVeprev** [comment] 2021-05-27 14:36
I work quite closely with the upstream, so I can apply a patch here and promote it to upstream. But for now I don't see a good solution: installing python part outside of the specified install prefix (in case of `CMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%`) looks definitely wrong to me. Assuming that `%LIBRARY_PREFIX%` is under `%PREFIX%` we can consider passing `CMAKE_INSTALL_PREFIX=%PREFIX%` and adding extra subdir `Library` for dlls/libs/headers and scripts installation, but I'm not sure if this way is reliable enough.

**Comment by sdebionne** [comment] 2021-05-27 16:34
I think we need different prefixes for the C++ libraries and the python binding. I checked oneTBB `python/CMakeLists.txt` and it's not clear to me how it installs into the proper `site-packages` (Windows and Unix have different folder layout for that as well) of the current python environment. Maybe using setuptools would be a more reliable option for the `tbb4py` subpackage?

**Comment by AlexVeprev** [comment] 2021-05-27 18:14
> I think we need different prefixes for the C++ libraries and the python binding.

Yes, that should work! I think there should not be any problem to use it in the recipe since tbb4py is configured separately: https://github.com/conda-forge/tbb-feedstock/blob/master/recipe/meta.yaml#L113

`tbb4py` installation works through setuptools under the hood:
1. Installation to `<build-dir-prefix>` in current build directory using setuptools: https://github.com/oneapi-src/oneTBB/blob/master/python/CMakeLists.txt#L39
2. Installation from the `<build-dir-prefix>` to the final `<prefix>` (`CMAKE_INSTALL_PREFIX`) https://github.com/oneapi-src/oneTBB/blob/master/python/CMakeLists.txt#L52

Do you think it is still may lead to problems because "Windows and Unix have different folder layout for that"?

**Comment by AlexVeprev** [comment] 2021-05-27 18:17
BTW, I had a chance to quickly check tbb-devel with a new layout (in the `Library`): it didn't work out-of-the-box for me in `find_package(TBB)` while the existing layout works without any preconfiguration. This looks strange to me, but I plan to check it more deeply.

**Comment by mgouicem** [comment] 2021-05-27 22:16
> @mgouicem, seems it is the root cause of the layout problem we recently talked about.

Yes, this is exactly the issue I was raising at some point. And we worked around it in oneDNN feedstock by setting `CMAKE_PREFIX_PATH=%PREFIX%` (see [this patch ](https://github.com/conda-forge/onednn-feedstock/commit/7b6204fb981070ce9d0cfe5bceb8b7f9e23e8196)). Thanks for looking into it.

**Comment by sdebionne** [comment] 2021-05-28 06:46
> BTW, I had a chance to quickly check tbb-devel with a new layout (in the `Library`): it didn't work out-of-the-box for me in `find_package(TBB)` while the existing layout works without any preconfiguration. This looks strange to me, but I plan to check it more deeply.

On Windows, when building a downstream project -one that uses oneTBB for instance, you need to set at least `-DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%`. This will ensure that TBB will be found with `find_package(TBB)`. Here are typical configure/build commands that works for CMake projects in  `conda-build`:

```
cmake -Bbuild -H. -G "Ninja" -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% -DCMAKE_FIND_ROOT_PATH=%LIBRARY_PREFIX% -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
cmake --build build --target install
```

**Comment by sdebionne** [comment] 2021-05-28 06:49
> > @mgouicem, seems it is the root cause of the layout problem we recently talked about.
> 
> Yes, this is exactly the issue I was raising at some point. And we worked around it in oneDNN feedstock by setting `CMAKE_PREFIX_PATH=%PREFIX%` (see [this patch ](https://github.com/conda-forge/onednn-feedstock/commit/7b6204fb981070ce9d0cfe5bceb8b7f9e23e8196)). Thanks for looking into it.

Well, the patch probably makes it work, but it also propagate the same issue to OneDNN. So I think it should reverted as soon as OneTBB has been fixed.

**Comment by AlexVeprev** [comment] 2021-06-17 12:03
I'd plan the fix on oneTBB 2021.3.0 update to avoid (potentially) breaking changes within one version. Please let me know if you have any objections.

**Comment by mgouicem** [comment] 2021-06-18 20:29
No objection on my side. @igorsafo, @xhochy  for a heads up.

**Comment by AlexVeprev** [comment] 2021-07-01 15:07
Should be fixed 2021.3.0.

**Comment by AlexVeprev** [comment] 2021-07-05 07:43
Please try 2021.3.0.

**Closed by AlexVeprev** 2021-07-05 07:43 UTC

**Comment by sdebionne** [comment] 2021-07-05 12:31
2021.3.0 works for me, thanks!
