### ISSUE TITLE
[FR] Automated updates for new releases

### ISSUE THREAD

**Issue by anton-malakhov** [conda-forge/tbb-feedstock#29] opened 2018-05-10 16:27 UTC
Feature idea:
I'm looking for a way to automatically trigger new tbb-feedstock PR whenever a new version is released at https://github.com/01org/tbb
they might want to introduce public CI as well, so, part of the scripting can go into TBB's repo. Is there any established precedent for this? Any suggestions? Thanks!

**Comment by jakirkham** [comment] 2018-06-05 20:20
Yeah, basically every 6hrs IIRC the autoupdate bot runs and sends update PRs to a handful of feedstocks. So this should just work. 🍀

We should check with @CJ-Wright that the format here looks ok for the bot.

**Comment by CJ-Wright** [comment] 2018-06-05 20:27
Might I also suggest [rever](https://regro.github.io/rever-docs/). Rever is a tool for automating software releases and forms the backbone of the bot's conda-forge PRing capability. Rever is both conda (`conda install -c conda-forge rever`) and pip (`pip install re-ver`) installable.

**Comment by CJ-Wright** [comment] 2018-06-05 20:31
The bot may not be that friendly to this setup currently. However, I think that will be fixed in the near future. xref: https://github.com/regro/cf-scripts/issues/165 and https://github.com/regro/cf-scripts/pull/166

**Comment by jakirkham** [comment] 2018-06-05 20:45
Thanks @CJ-Wright. Good think I checked before promising the moon. 😄

Do you know what timeline you are looking for this functionality on, @anton-malakhov?

**Comment by anton-malakhov** [comment] 2018-06-05 20:52
I believe we have plenty of time (2 months?) before the next TBB 2019 release, unless they face a need in some out-of-bound customer or bug-fix release.

**Comment by anton-malakhov** [comment] 2018-06-19 19:13
Actually, they decided to do 2018.0.5 release https://github.com/01org/tbb/releases/tag/2018_U5 with ARMv8 and better huge pages support in allocator

**Comment by anton-malakhov** [comment] 2018-06-20 20:29
@jakirkham @isuruf Is the auto-update bot online? TBB 2018_U5 is out, but I don't see any PR being automatically created for that

**Comment by CJ-Wright** [comment] 2018-06-20 20:36
No the bot is currently offline for maintenance. I'm hoping to get it back online soon.

**Comment by anton-malakhov** [comment] 2018-06-20 20:38
thanks, CJ! Please let me know if it cannot create the PR for tbb-feedstock

**Comment by anton-malakhov** [comment] 2018-06-27 16:16
There is still no PR :(

**Comment by CJ-Wright** [comment] 2018-06-27 16:32
The bot's error for this is `Upstream: no url in yaml`.
I'm not exactly certain what is going on here.
@isuruf @justcalamari thoughts?

**Comment by CJ-Wright** [comment] 2018-06-27 16:33
Just for reference here is what the bot has for tbb
```python
In [11]: pprint(g.node['tbb'])
{'PRed': [{'migrator_name': 'Version',
           'migrator_version': 0,
           'version': '2018'}],
 'bad': 'Upstream: no url in yaml',
 'feedstock_name': 'tbb',
 'hash_type': 'sha256',
 'meta_yaml': {'about': {'dev_url': 'https://github.com/01org/tbb',
                         'doc_url': 'https://software.intel.com/en-us/node/506039',
                         'home': 'http://www.threadingbuildingblocks.org',
                         'license': 'Apache 2.0',
                         'license_file': 'LICENSE',
                         'summary': 'High level abstract threading library'},
               'build': {'number': '0', 'script_env': None},
               'extra': {'recipe-maintainers': ['jschueller',
                                                'anton-malakhov']},
               'outputs': [{'build': {'script': 'python build/build.py '
                                                '--build-args="stdver=c++11 '
                                                'CXXFLAGS= CFLAGS=" '
                                                '--install-libs'},
                            'name': 'tbb'},
                           {'build': {'script': 'python build/build.py '
                                                '--build-args="stdver=c++11 '
                                                'CXXFLAGS= CFLAGS=" '
                                                '--no-rebuild --install-devel '
                                                '--install-docs'},
                            'name': 'tbb-devel',
                            'requirements': {'build': ['python *',
                                                       'cxx_compiler_stub'],
                                             'run': ['subpackage_stub']},
                            'test': {'commands': ['test -f '
                                                  '${PREFIX}/include/tbb/tbb.h']}},
                           {'about': {'dev_url': 'https://github.com/01org/tbb',
                                      'license': 'Apache 2.0',
                                      'summary': 'TBB module for Python'},
                            'build': {'entry_points': ['python-tbb = '
                                                       'tbb:_main'],
                                      'script': 'python build/build.py '
                                                '--build-args="stdver=c++11 '
                                                'CXXFLAGS= CFLAGS=" '
                                                '--no-rebuild '
                                                '--install-python'},
                            'name': 'tbb4py',
                            'requirements': {'build': ['cxx_compiler_stub',
                                                       'swig'],
                                             'host': ['python',
                                                      'subpackage_stub'],
                                             'run': ['tbb >=2018.0.4',
                                                     'python']},
                            'test': {'commands': ['python-tbb -h',
                                                  'python -m TBB -h',
                                                  'python -m tbb -h',
                                                  'python -m tbb test'],
                                     'imports': ['tbb', 'TBB'],
                                     'requires': ['python',
                                                  'subpackage_stub']}}],
               'package': {'name': 'tbb', 'version': '2018.0.4'},
               'requirements': {'build': ['python *', 'cxx_compiler_stub']},
               'source': {'fn': 'tbb2018_U4_oss_src.tgz',
                          'sha256': 'd5604a04787c8a037d4944eeb89792e7c45f6a83c141b20df7ee89c2fb012ed1',
                          'url': 'https://github.com/01org/tbb/archive/2018_U4.tar.gz'},
               'test': {'commands': ['python -c "import ctypes; assert 10004 '
                                     "== ctypes.cdll[r'libtbb.so.2']       "
                                     '[\'TBB_runtime_interface_version\']()"'],
                        'requires': ['python *']}},
 'name': 'tbb',
 'new_version': '2018_U5',
 'raw_meta_yaml': '{% set version = "2018.0.4" %}\n'
                  '\n'
                  "{% set year = version.split('.')[0]|int %}\n"
                  "{% set update = version.split('.')[2]|int %}\n"
                  '{% if update == 0 %}\n'
                  '{%   set vtag = "%d" % year %}\n'
                  '{% else %}\n'
                  '{%   set vtag = "%d_U%d" % (year, update) %}\n'
                  '{% endif %}\n'
                  '{% set vinterface = (year-2008)*1000 + update %}  # just '
                  'guess, does not fit the previous versions before 2018\n'
                  '\n'
                  "{% set build = 'python build/build.py "
                  "--make-tool=mingw32-make --build-prefix=vc%VS_MAJOR%' %}  # "
                  '[win]\n'
                  "{% set build = 'python build/build.py "
                  '--build-args="stdver=c++11 CXXFLAGS= CFLAGS="\' %}         '
                  '# [unix]\n'
                  '\n'
                  'package:\n'
                  '  name: tbb\n'
                  '  version: {{ version }}\n'
                  '\n'
                  'source:\n'
                  '  fn: tbb{{ vtag }}_oss_src.tgz\n'
                  '  url: https://github.com/01org/tbb/archive/{{ vtag '
                  '}}.tar.gz\n'
                  '  sha256: '
                  'd5604a04787c8a037d4944eeb89792e7c45f6a83c141b20df7ee89c2fb012ed1\n'
                  '\n'
                  'build:\n'
                  '  number: 0\n'
                  '  script_env:\n'
                  '    - OS    # [win]\n'
                  '\n'
                  'requirements:\n'
                  '  build:\n'
                  '    - python *\n'
                  "    - {{ compiler('cxx') }}\n"
                  '    - m2w64-make                                         # '
                  '[win]\n'
                  '\n'
                  'test:\n'
                  '  requires:\n'
                  '    - python *               # any python version is ok for '
                  'sake of testing of shared libraries\n'
                  '  commands:\n'
                  '    - python -c "import ctypes; assert {{ vinterface }} == '
                  "ctypes.cdll[r'libtbb.so.2']       "
                  '[\'TBB_runtime_interface_version\']()"  # [linux]\n'
                  '    - python -c "import ctypes; assert {{ vinterface }} == '
                  'ctypes.cdll[r\'libtbb${SHLIB_EXT}\'][\'TBB_runtime_interface_version\']()"  '
                  '# [unix and not linux]\n'
                  '    - python -c "import ctypes; assert {{ vinterface }} == '
                  "ctypes.cdll[r'tbb.dll']           "
                  '[\'TBB_runtime_interface_version\']()"  # [win]\n'
                  '\n'
                  'outputs:\n'
                  '  - name: tbb\n'
                  '    build:\n'
                  '      script: {{ build }} --install-libs\n'
                  '\n'
                  '  - name: tbb-devel\n'
                  '    build:\n'
                  '      script: {{ build }} --no-rebuild --install-devel '
                  '--install-docs\n'
                  '    requirements:\n'
                  '      build:\n'
                  '        - python *\n'
                  "        - {{ compiler('cxx') }}\n"
                  '        - m2w64-make                                     # '
                  '[win]\n'
                  '      run:\n'
                  "        - {{ pin_subpackage('tbb', exact=True) }}        # "
                  'development package is for specific version of tbb\n'
                  '    test:\n'
                  '      commands:\n'
                  '        - if not exist '
                  '%PREFIX%\\Library\\include\\tbb\\tbb.h exit 1  # [win]\n'
                  '        - if not exist %PREFIX%\\Library\\lib\\tbb.lib exit '
                  '1        # [win]\n'
                  '        - test -f '
                  '${PREFIX}/include/tbb/tbb.h                     # [unix]\n'
                  '\n'
                  '  - name: tbb4py\n'
                  '    build:\n'
                  '      script: {{ build }} --no-rebuild --install-python\n'
                  '      entry_points:\n'
                  '        - python-tbb = tbb:_main\n'
                  '    requirements:\n'
                  '      build:\n'
                  "        - {{ compiler('cxx') }}\n"
                  '        - m2w64-make                                     # '
                  '[win]\n'
                  '        - swig\n'
                  '      host:\n'
                  '        - python\n'
                  "        - {{ pin_subpackage('tbb-devel', exact=True) }}\n"
                  '      run:\n'
                  '        - tbb >={{ version }}                            # '
                  'while python module works with any compatible tbb...\n'
                  '        - python\n'
                  '    test:\n'
                  '      requires:\n'
                  '        - python\n'
                  "        - {{ pin_subpackage('tbb', exact=True) }}        # "
                  'we want to test with this specific tbb package\n'
                  '      imports:\n'
                  '        - tbb\n'
                  '        - TBB\n'
                  '      commands:\n'
                  '        - python-tbb -h\n'
                  '        - python -m TBB -h\n'
                  '        - python -m tbb -h\n'
                  '        - python -m tbb test\n'
                  '    about:\n'
                  '      summary: TBB module for Python\n'
                  '      license: Apache 2.0\n'
                  '      dev_url: https://github.com/01org/tbb\n'
                  '\n'
                  'about:\n'
                  '  home: http://www.threadingbuildingblocks.org\n'
                  '  license: Apache 2.0\n'
                  '  license_file: LICENSE\n'
                  '  summary: High level abstract threading library\n'
                  '  dev_url: https://github.com/01org/tbb\n'
                  '  doc_url: https://software.intel.com/en-us/node/506039\n'
                  '\n'
                  'extra:\n'
                  '  recipe-maintainers:\n'
                  '    - jschueller\n'
                  '    - anton-malakhov\n',
 'req': {'cxx_compiler_stub', 'python'},
 'time': 1530053943.5890245,
 'url': 'https://github.com/01org/tbb/archive/2018_U4.tar.gz',
 'version': '2018.0.4'}
```

**Comment by anton-malakhov** [comment] 2018-06-27 16:48
that's not clear, the url is there, in your output it towards the end of the log: ` 'url': 'https://github.com/01org/tbb/archive/2018_U4.tar.gz'`

**Comment by CJ-Wright** [comment] 2018-06-27 16:55
Right, so the issue is not that URL but the URL we predict will be the next URL. 
The relevant line is here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py#L157

The basic idea of `RawURL` is to try to predict the next url by updating an internal copy of the `meta.yaml` with a next version and seeing what the URL would be and if that URL exists. If the URL exists then we use it to bump the version. (@isuruf please correct me if this explanation is missing anything)

It seems that when we do the replacement something goes sideways and we can't find a URL, potentially because we aren't parsing correctly??

**Comment by isuruf** [comment] 2018-06-27 18:13
@CJ-Wright, I think https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py#L153 should be changed to something like,

```
if 'url' in s and s['url'] != meta_yaml["source"]["url"]:
```

**Comment by CJ-Wright** [comment] 2018-06-27 18:50
xref: https://github.com/regro/cf-scripts/pull/216#issuecomment-400787026

**Comment by isuruf** [comment] 2018-06-27 18:56
It still won't work, because the version is `2018.0.5`, but `0` has no significance on the URL. This is a strange case, that I don't think the bot can handle. Maybe the version should just be `2018.5`

**Comment by CJ-Wright** [comment] 2018-06-27 19:07
Do we re-parse the meta.yaml with the new version in it? If so then it should be ok, assuming that all the jinja2 wrangling produces the correct URL, right?

**Comment by isuruf** [comment] 2018-06-27 19:08
Issue is that RawURL would check `2018.1.0`, which translates to `https://github.com/01org/tbb/archive/2018.tar.gz`, but this is the same URL you would get for `2018.0.0`.

**Comment by CJ-Wright** [comment] 2018-06-27 19:15
Why is it looking at that URL should `vtag` be "2018_U5" from the jinja2?

**Comment by isuruf** [comment] 2018-06-27 19:17
First it looks at 2018.0.5 which is found and then looks at 2018.1.0 which is found and then at 2019.1.1 which is found and so on until 2018.1.5 and then 2019.0.0 which is not found.

**Comment by CJ-Wright** [comment] 2018-06-27 19:29
This is a moot point since 2018_U5 went in.

**Comment by justcalamari** [comment] 2018-06-27 19:38
Yeah the version probably should just be "2018.5". I think now the bot will check "2018.1.0", find the url "https://github.com/01org/tbb/archive/2018.tar.gz" and create an update PR, even though this package already exists as version "2018.0.0".

**Comment by CJ-Wright** [comment] 2018-06-27 19:39
xref: https://github.com/conda-forge/tbb-feedstock/issues/31

**Comment by anton-malakhov** [comment] 2018-09-14 19:56
We've finally got the automatically created PR! Though, since TBB and Intel's Parallel Studio in general changed versioning scheme to YEAR.UPDATE (two digits) from YEAR.0.UPDATE, it might break the bot again, I've implemented some changes, will see if it works with the next update.

**Comment by anton-malakhov** [comment] 2018-12-05 22:39
One day passed since new release (2019_U3) but there is no new PR created

**Comment by jakirkham** [comment] 2018-12-05 22:42
Could you please raise on [this issue tracker]( https://github.com/regro/cf-scripts/issues )?

**Comment by anton-malakhov** [comment] 2018-12-05 23:17
The bot logs have nothing suspicious: https://circleci.com/gh/regro/circle_worker/tree/master

**Comment by isuruf** [comment] 2018-12-05 23:22
From the logs, bot picked up that there was a new version. Not sure why there was no PR issued though

```
2018-12-05 23:12:49,344 INFO     conda_forge_tick.update_upstream_versions || tbb - 2019.2 - 2019.3
```

**Closed** 2018-12-06 00:57 UTC
