### ISSUE TITLE
libtbb.so is not found

### ISSUE THREAD

**Issue by looooo** [conda-forge/tbb-feedstock#40] opened 2018-09-24 07:04 UTC
For backward compatibility please add this link for linux and osx.

I struggled to understand why some of my builds were failing recently [1] but I think this is the issue.

[1]https://circleci.com/gh/looooo/freecad-feedstock/22
```
ninja: error: '/home/conda/feedstock_root/build_artifacts/freecad_1537682978936/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/libtbb.so', needed by 'Mod/Part/Part.so', missing and no known rule to make it
```

**Comment by anton-malakhov** [comment] 2018-09-24 16:10
I guess this is duplicate of #38. If you want to build something with tbb, you need `tbb-devel` which contains `libtbb.so` and header files.

Please note though that using a link `.so` to `.so.2` is incorrect approach which used to be used in this feedstock by mistake. TBB project uses linker scripts instead - the same approach as some system libraries on Linux. While your OS X compilation is broken not because of the link but because of absence of the header files - so, list `tbb-devel` as your build dependency.

**Comment by looooo** [comment] 2018-09-24 18:58
thanks for the reply, but I need some more help:

my package doesn't directly depend on tbb. There are two dependencies (occt, vtk) which both depend on tbb. So I guess these dependencies must be updated to make the freecad-build work again. I guess mixing different tbb-versions is not an option.
Maybe you can have a look at https://github.com/conda-forge/occt-feedstock/blob/master/recipe/meta.yaml#L29L34 . I guess the pin_compatible isn't necessary anymore as tbb uses run_esports.

**Comment by anton-malakhov** [comment] 2018-09-24 21:38
Right, these modules should both use tbb through conda's dependencies in order to avoid duplication,

> I guess the pin_compatible isn't necessary anymore as tbb uses run_esports.
yes, it theory, it should work if you just leave `tbb-devel` in your `host:` dependencies. it also has excessive dependence on `tbb` in `host:` section as `tbb-devel` depends on it as well.

**Comment by looooo** [comment] 2018-09-28 08:44
so every package that somehow depends on tbb (eg. depending on a tbb-dependent package) and is compiled now needs to specify tbb-devel as build-dependency. I wonder if this is really the way to proceed...

**Comment by looooo** [comment] 2018-09-28 08:56
@anton-malakhov wouldn't it be possible to call the resulting library libtbb.so without any numbered suffix? I guess this would solve the problem for freecad and smesh which are both libraries not depending directly on tbb.

**Comment by looooo** [comment] 2018-09-29 07:40
ok, sounds difficult and seems to be not very logic. But anyway, I will include the tbb-devel in all occt/vtk dependent packages...

Regarding the naming:

> no these numbers protect from backward compatibility issues (besides highlighting design and build mistakes :) ).

I guess stuff like this makes sense for any system-packages... But for conda we have environments to separate different versions. I don't think there is the need to install different versions in the same environment. Anyway these numbers are only workarounds. In an ideal system/distribution I don't think you want to have more versions of the same package. So these things should be handled by the system-packaging tool and not by the configuration of the package. (At least in my (quite limited) view : ) )

**Comment by looooo** [comment] 2018-09-29 08:55
@anton-malakhov btw. as you also have seen with the PR on freecad-feedstock including tbb-devel doesn't solve the problem. Also recompiling tbb-dependent packages (vtk, occt) doesn't solve this issue. I guess it's a strong sign that there is something wrong with the tbb-package...

**Comment by looooo** [comment] 2018-09-29 09:36
the latest occt looks good:
```
(occt) k@sm:~/conda/envs/occt/lib$ ldd libTKXCAF.so |grep tbb
	libtbb.so.2 => /home/k/conda/envs/occt/lib/././libtbb.so.2 (0x00007f1d38e1b000)
	libtbbmalloc.so.2 => /home/k/conda/envs/occt/lib/././libtbbmalloc.so.2 (0x00007f1d38bdd000)
```
also vtk looks good:
```
(occt) k@sm:~/conda/envs/occt/lib$ ldd libvtkGeovisCore-8.1.so |grep tbb
	libtbb.so.2 => /home/k/conda/envs/occt/lib/././libtbb.so.2 (0x00007feeb9a06000)
```

Maybe there is another tbb-dependent package involved which has to be updated?

**Comment by anton-malakhov** [comment] 2018-09-29 20:37
Does it work with previous version of tbb? If adding `tbb-devel` does not help, it is unlikely that any restructuring in the packaging is involved here since `tbb-devel` together with `tbb` contain all the files which old `tbb` package had.

FYI, "SONAME" is not invented by TBB project. Just execute `ls /usr/lib/*.so.*` in your Linux..

**Comment by anton-malakhov** [comment] 2018-10-01 02:13
As confirmed by the green status of https://github.com/looooo/freecad-feedstock/pull/1, your recipe needed `tbb-devel` to be added into host requirements. It also suggests it's likely that one or both of your libraries re-export TBB (through headers) as a build-time requirement for your application as described in case (2) of https://github.com/conda-forge/tbb-feedstock/issues/40#issuecomment-425565588

It's not pretty solution, I agree. Ideally, such a re-exporting library package must describe in its recipe that whenever it is being used, it needs `tbb-devel` as well. Unfortunately, it looks like conda-build cannot automatically add another entry to the same `host:` section when you add such a library as a host requirement. As a work-around, this library can declare `run-export: strong` for itself and `tbb-devel`, then you can put this library into `build:` section instead, so `host:` will be automatically populated through `run-export`. But this is not related to TBB feedstock anyway - please open a feature request against conda-build if you want to make it a little prettier.

Hereby, I consider this case closed.

**Closed by anton-malakhov** 2018-10-01 02:13 UTC
